# Generated by Django 5.1.15 on 2026-05-14 20:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "rustfs_path",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                (
                    "merchant_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("transaction_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "sales_tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("raw_llm_response", models.JSONField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, default="")),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-transaction_date", "-created_at"),
            },
        ),
    ]
